name: Test

on:
  push:
    branches: main
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest-16-core
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci
      - run: npm run test
        env:
          ELASTIC_APM_ENDPOINT: ${{ secrets.ELASTIC_APM_ENDPOINT }}
          ELASTIC_APM_TOKEN: ${{ secrets.ELASTIC_APM_TOKEN }}

  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest-16-core
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci
      - run: npm run test:e2e
        env:
          REDIS_HOST: ${{ vars.REDIS_HOST }}
          REDIS_PORT: ${{ vars.REDIS_PORT }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ELASTIC_APM_ENDPOINT: ${{ secrets.ELASTIC_APM_ENDPOINT }}
          ELASTIC_APM_TOKEN: ${{ secrets.ELASTIC_APM_TOKEN }}
